spring.application.name=candle-shop

spring.profiles.active=dev
server.port=${PORT:8080}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
app.jwt.secret=${JWT_SECRET:very-long-secret-key-for-candle-shop-change-it-later-very-long}
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173}
app.public-url=${APP_PUBLIC_URL:http://localhost:5173}
app.mail.from=${MAIL_FROM:no-reply@voskosvet.ru}
app.notifications.email=${NOTIFICATION_EMAIL:}

spring.mail.host=${MAIL_HOST:localhost}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS:false}
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_SSL:false}
app.frontend-url=${APP_FRONTEND_URL:http://localhost:5173}
yookassa.shop-id=${YOOKASSA_SHOP_ID:}
yookassa.secret-key=${YOOKASSA_SECRET_KEY:}
app.telegram.bot-token=${TELEGRAM_BOT_TOKEN:}
app.telegram.chat-id=${TELEGRAM_CHAT_ID:}
