spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
app.frontend-url=${APP_FRONTEND_URL:https://voskosvet.ru}

app.admin.username=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}

app.manager.username=${MANAGER_USERNAME}
app.manager.password=${MANAGER_PASSWORD}
