export type Candle = {
  id: number;
  slug: string;
  createdAt: string;
  name: string;
  description: string;
  shortDescription: string;
  seoTitle: string | null;
  seoDescription: string | null;
  material: string | null;
  wickType: string | null;
  usageInstructions: string | null;
  price: number;
  scent: string;
  color: string;
  size: string | null;
  weightGrams: number;
  burnTimeHours: number;
  imageUrl: string;
  imageUrls: string[];
  imageAlts: Record<string, string>;
  available: boolean;
  featured: boolean;
  categoryId: number;
  categoryName: string;
  priceTiers: Array<{
    quantity: number;
    unitPrice: number;
    imageUrl?: string;
  }>;
};
