CREATE TABLE candle_sizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value_cm INTEGER NOT NULL UNIQUE,
    CONSTRAINT chk_candle_sizes_positive CHECK (value_cm > 0)
);

INSERT INTO candle_sizes (value_cm)
VALUES (15), (20), (30), (40), (45);
