CREATE TABLE media_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(100) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    data BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(255) NOT NULL,
    review_text VARCHAR(1000) NOT NULL,
    rating INTEGER NOT NULL,
    image_url VARCHAR(500),
    author_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_author FOREIGN KEY (author_id) REFERENCES customers(id),
    CONSTRAINT chk_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

INSERT INTO reviews (display_name, review_text, rating) VALUES
('Полина Ш.', 'Чистый пчелиный воск, без примесей. Горят ровно, не капают, запах приятный и медовый.', 5),
('Анастасия', 'Свечи пришли аккуратно упакованными. Очень красивый тёплый цвет, сразу видно ручную работу.', 5),
('Екатерина К.', 'Фитиль ровный, свеча не течёт, горит спокойно и долго. Качеством очень довольна.', 5);
